image: continuumio/miniconda3:latest

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda update -n base conda
  - conda env create -f environment.yml
  - source activate tim
  - pip install -e .

tests:
  script:
    - cd gistim/test
    - python -m pytest --cache-clear
    - cd ..
    - black --check . 
