image: condaforge/miniforge3

stages:
  - lint
  - test
  - publish

before_script:
  - pip install tox
    
lint:
  script:
    - tox -e lint

test:
  script:
    - tox -e test

pages:
  stage: publish
  script:
  - tox -e docs
  - mv .tox/docs_out/ public/
  artifacts:
    paths:
    - public
  only:
  - master
