name: tim 

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - geopandas
  - matplotlib
  - netCDF4
  - numba>=0.50
  - numpy
  - pandas
  - python>=3.7
  - scipy
  - timml
  - ttim
  - xarray>=0.15
