[mypy]
python_version = 3.11
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
strict_equality = True
extra_checks = True
disallow_subclassing_any = True
disallow_untyped_decorators = True
disallow_any_generics = True

[mypy-qgis.*]
ignore_missing_imports = True
