---
title: "Install"
---

QGIS-Tim consists of two parts: A QGIS plugin and the ``gistim`` Python
package, which runs in a separate Python environment. The installation of
QGIS-Tim therfore consists of three steps:

## 1. Install QGIS

Download and install a recent version of QGIS (>3.22):
<https://www.qgis.org/en/site/forusers/download.html>{target="_blank"}

## 2. Install ``gistim`` in a seperate Python environment

``gistim`` requires a seperate Python environment, because it depends on
packages incompatible with the packages in QGIS' own Python environment. There
are two approaches: either using the fully-fletched Deltaforge distribution
(Recommended) or the leaner Miniforge distribution.

### Method 1: with Deltaforge (Recommended)

[Download and install Deltaforge](
https://download2.deltares.nl/imod-suite/){target="_blank"}. 
**Make sure you use Deltaforge version 0.3.0 or higher!**

1. Open the Deltaforge prompt (search in Windows Start for \"Deltaforge
    Prompt\").
2. Configure the gistim installation, so that the QGIS plugin is able
    to find it. Run: ``python -m gistim configure``

### Method 2: with Miniforge

[Download and install a miniforge Python installation](
https://github.com/conda-forge/miniforge){target="_blank"}


1.  Open the miniforge prompt (search in Windows Start for \"Miniforge
    Prompt\").
2.  Create a new conda environment, run: conda create \--name tim
    python=3.9
3.  Activate the environment: conda activate tim
4.  Run: conda install -c conda-forge gistim
6.  Configure the gistim installation, so that the QGIS plugin is able
    to find it. Run: ``python -m gistim configure``

## 3. Install the QGIS plugin
 
### Method 1: From the GQIS plugin database 
**NB** Due to ongoing developments new features and bug fixes might not be part of this release. Consider installation method 2.


1.  Open QGIS.
3.  At the top, find the Plugins menu (\~sixth object in the menubar).
4.  Find \"Manage and Install plugins\" (\~first object in drop-down).
5.  Find \"All\" (\~first in left section).
6.  Search for \"Qgis-Tim\".
7.  Click \"Install Plugin\".

### Method 2: From Zip (prefered) 
1.  Download the \"QGIS-TIM-plugin.zip\" (do not unzip!) from the [iMOD-Suite download portal.](https://deltares.thegood.cloud/s/AefTz97ZHbWS4RT){target="_blank"}
2.  Open QGIS.
3.  At the top, find the Plugins menu (\~sixth object in the menubar).
4.  Find \"Manage and Install plugins\" (\~first object in drop-down).
5.  Find \"Install from ZIP\" (\~fourth in left section).
6.  Enter the path to the file \"QGIS-TIM-plugin.zip\".
7.  Click \"Install Plugin\".

This will add an icon to the toolbar(s). By clicking the icon, the plugin is
started. The QGIS plugin will automatically start and external interpreter when
it is required.
