name: release

on:
  push:
    branches:
    - main
    tags:
      - '*'

jobs:
  build:
    name: Release ${{ matrix.os }} PyInstaller
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.4.1
      - name: Build with PyInstaller
        run: pixi run build-backend
      - name: Create ZIP Archive
        run: pixi run create-archive
      - name: Release
        run: gh release upload ${{ github.ref_name }} dist/gistim-${{ RUNNER_OS }}.zip sha256-${{ RUNNER_OS }}.txt
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
 