name: release

on:
  push:
    branches:
    - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      content: write
    matrix:
      os:
        - windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.4.1
      - name: Build with PyInstaller
        run: pixi run build-backend
      - name: Create ZIP Archive
        run: pixi run create-archive
      - name: Release
        run: gh release create ${{github.ref_name}} dist/gistim-Windows.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
 